appVersion: 1.3.0
description: IBM Event Streams based on Apache Kafka.
icon: https://raw.githubusercontent.com/IBM/event-streams/master/es/es_icon_light.png
keywords:
- kafka
- amd64
- s390x
- Limited
- ICP
- Integration
kubeVersion: '>=1.11.0'
name: ibm-eventstreams-dev
tillerVersion: '>=2.9.1'
version: 1.3.0
