{{- if .Values.prometheus.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ include "uistio.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}-prometheus
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
spec:
  hosts:
  - prometheus.{{ .Release.Namespace }}.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: {{ .Values.prometheus.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "uistio.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}-prometheus
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
spec:
  host: prometheus.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "uistio.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}-prometheus
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
spec:
  hosts:
  - {{ .Values.prometheus.host }}
  http:
  - route:
    - destination:
        host: prometheus.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
