apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uistio.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "uistio.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
  - namespaces
  - services
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["istio.banzaicloud.io"]
  resources:
  - istios
  - remoteistios
  verbs:
  - get
  - list
  - watch
  - edit
- apiGroups: ["networking.istio.io"]
  resources:
  - destinationrules
  - virtualservices
  - gateways
  verbs:
  - create
  - get
  - list
  - watch
  - edit
  - update
  - patch
  - delete
- apiGroups: ["istio.banzaicloud.io"]
  resources:
  - canaries
  verbs:
  - create
  - get
  - list
  - watch
  - edit
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "uistio.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "uistio.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "uistio.name" . }}
  namespace: {{ .Release.Namespace }}
