apiVersion: v1
kind: Service
metadata:
  name: {{ include "uistio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
spec:
  type: {{ .Values.application.service.type }}
  ports:
    - port: {{ .Values.application.service.port }}
      targetPort: http-app
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uistio.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "uistio.name" . }}-web
    helm.sh/chart: {{ include "uistio.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ include "uistio.name" . }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "uistio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
