appVersion: 0.14.0
description: Helm chart for Kubernetes. Provides the Graphical User Interface for
  Pipeline PaaS
home: https://banzaicloud.com
keywords:
- pipeline-ui
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: pipeline-ui
sources:
- https://github.com/banzaicloud/banzai-charts/
version: 1.1.4
