{{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled }} 

kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fullname" . }}-kafka-secrets
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app.type: lenses-secret
data:
  {{- if .Values.kafka.ssl.enabled }}
  client.truststore.jks: {{ .Values.kafka.ssl.trustStoreFileData }}
  client.keystore.jks: {{ .Values.kafka.ssl.keyStoreFileData }}
  {{- end }}
stringData:
  {{- if .Values.kafka.sasl.enabled }}
  jaas.conf: |-
{{ .Values.kafka.sasl.jaasFileData | default "" | indent 4 }}
  keytab: |-
{{ .Values.kafka.sasl.keyTabData | default "" | indent 4 }}
  {{- end }}
{{- end -}}  
