apiVersion: v1
appVersion: 0.1.0
description: Helm chart for istiocni components
engine: gotpl
icon: https://raw.githubusercontent.com/IBM/charts/master/logo/istio-logo.png
keywords:
- istiocni
- istio
name: istiocni
sources:
- https://github.com/istio/cni
tillerVersion: '>=2.7.2-0'
version: 1.1.7
