apiVersion: v1
appVersion: 'elasticsearch: 7.2.1-0; kibana: 7.2.1-0; fluentd-elasticsearch: 4.3.2;
  apm-server: 2.1.4'
description: A Helm chart containing ELK for Kubernetes
name: efk
version: 7.1.0
