---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "exoip.fullname" . }}-credentials
  labels:
    app.kubernetes.io/name: {{ include "exoip.name" . }}
    helm.sh/chart: {{ include "exoip.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  exoscale_api_key: {{ required "Exoscale API key is required" .Values.exoscaleApiKey | b64enc | quote }}
  exoscale_api_secret: {{ required "Exoscale API secret is required" .Values.exoscaleApiSecret | b64enc | quote }}
