apiVersion: v1
appVersion: amd64-2.0.0.5321-ls62
description: Sonarr is a television show downloading client
home: https://github.com/billimek/billimek-charts/tree/master/sonarr
icon: https://avatars1.githubusercontent.com/u/1082903?s=400&v=4
keywords:
- sonarr
- usenet
- bittorrent
maintainers:
- email: jeff@billimek.com
  name: billimek
name: sonarr
sources:
- https://hub.docker.com/r/linuxserver/sonarr/
- https://sonarr.tv/
version: 2.0.7
