appVersion: 0.1.12
description: FADI is a Cloud Native platform for Big Data based on mature open source
  tools.
home: https://github.com/cetic/fadi
icon: https://raw.githubusercontent.com/cetic/fadi/master/doc/images/logo.png
keywords:
- fadi
- cetic
- bigdata
- nifi
- spark
- grafana
- cassandra
- kafka
maintainers:
- name: alexnuttinck
- name: banzo
- name: AyadiAmen
name: fadi
version: 0.1.12
