{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "haproxytech-ingress.name" . }}
    chart: {{ template "haproxytech-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "haproxytech-ingress.serviceAccountName" . }}
{{- end -}}
