{{- if .Values.metrics.prometheusOperator }}
{{- $ns_selector :=  printf "namespace=\"%s\"" .Release.Namespace }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "stardog.fullname" . }}-rules
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    role: alert-rules
spec:
  groups:
  - name: Stardog
    rules:
    - alert: StardogOpenConnections
      expr: stardog_database_openconnections{ {{ $ns_selector }} } > 32
      for: 1m
      annotations:
        summary: Too many open connections
        description: Open connections for DB {{ "{{" }} $labels.database {{ "}}" }} on instance {{ "{{" }} $labels.pod {{ "}}" }} exeeded 32 ({{ "{{" }} $value {{ "}}" }}).
      labels:
        env: {{ .Release.Name }}
        app: stardog
        severity: critical
    - alert: StardogLicenseExpire
      expr: stardog_dbms_license_expiration_value{ {{ $ns_selector }} } < 42
      for: 10m
      annotations:
        summary: Stardog license about to expire
        description: The Stardog license will expire in {{ "{{" }} $value {{ "}}" }} days.
      labels:
        env: {{ .Release.Name }}
        app: stardog
        severity: "{{ "{{ if lt $value 21.0 }}" }}critical{{ "{{ else }}" }}warning{{ "{{ end }}" }}"
{{- end }}
