apiVersion: v1
description: Mock-Pathfinder Helm chart for Kubernetes
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
maintainers:
- email: miguel.debarros@modusbox.com
  name: Miguel de Barros
name: mockpathfinder
sources:
- https://github.com/mojaloop/mojaloop
- https://github.com/mojaloop/helm
- https://github.com/mojaloop/mock-pathfinder
version: 2.4.0
