apiVersion: "logging.banzaicloud.com/v1alpha1"
kind: "Plugin"
metadata:
  name: {{ include "nginx-logging-demo.fullname" . }}
  labels:
    app: {{ include "nginx-logging-demo.name" . }}
    chart: {{ include "nginx-logging-demo.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  input:
    label:
      app: {{ include "nginx-logging-demo.name" . }}
{{- if .Values.forwarding.enabled }}
  output:
    - type: forward
      name: forward
      parameters:
        - name: host
          value: {{ .Values.forwarding.targetHost | quote }}
        - name: port
          value: {{ .Values.forwarding.targetPort | quote }}
        - name: name
          value: {{ .Values.forwarding.targetHost | quote }}
{{- if .Values.forwarding.tlsSharedKey }}
        - name: tlsSharedKey
          value: {{ .Values.forwarding.tlsSharedKey | b64enc | quote }}
{{- end }}
{{- end }}
  filter:
    - type: parser
      name: parser-nginx
      parameters:
        - name: format
          value: '/^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"(?:\s+(?<http_x_forwarded_for>[^ ]+))?)?$/'
        - name: timeFormat
          value: "%d/%b/%Y:%H:%M:%S %z"