---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: {{ .Values.name | quote }}
  labels: 
    pvc: {{ .Values.persistentVolumeClaimLabel }}
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  capacity:
    storage: {{ .Values.capacity | quote }}
  accessModes: 
    - {{ .Values.accessMode | quote }}
  azureFile:
    secretName: {{ .Values.secretsRef | quote }}
    shareName: {{ .Values.azureFile.shareName | quote }}     
    readOnly: {{ .Values.azureFile.readOnly  }}