{{ if .Values.catalog }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: catalog
    version: v1
{{ include "backyards-demo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "cinema catalog response"
        - name: REQUESTS
          value: "http://movies:8080/#1"
{{ end }}
