{{ if .Values.moviesv2 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app: movies
    version: v2
{{ include "backyards-demo.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movies
        version: v2
    spec:
      containers:
      - name: movies
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "movies list response v2"
{{ end }}
