{{ if .Values.moviesv3 }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies-v3
  namespace: {{ .Release.Namespace }}
  labels:
    app: movies
    version: v3
{{ include "backyards-demo.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movies
        version: v3
    spec:
      containers:
      - name: movies
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "movies list response v3"
{{ end }}
