{{ if .Values.notifications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: notifications
    version: v1
{{ include "backyards-demo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: notifications
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notifications
        version: v1
    spec:
      containers:
      - name: notifications
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "notification sent"
{{ end }}
