apiVersion: v1
data:
  cluster-agent-config.json: |
    {
    "ControllerUrl": {{ .Values.controller.url | quote}},
    "Account": {{ .Values.controller.accountName | quote}},
    "GlobalAccount": {{ .Values.controller.globalAccountName | quote}},
    "EventServiceUrl": {{ .Values.analytics.eventEndpoint | quote}},
    "AppName": {{ .Values.agent.appName | quote }},
    "TierName": {{ .Values.agent.tierName | quote }},
    "NodeName": "Node1",
    "SystemSSLCert": "/opt/appdynamics/ssl/system.crt",
    "AgentSSLCert": "/opt/appdynamics/ssl/agent.crt",
    "EventAPILimit": 100,
    "PodSchemaName": "kube_pod_snapshots",
    "NodeSchemaName": "kube_node_snapshots",
    "EventSchemaName": "kube_event_snapshots",
    "ContainerSchemaName": "kube_container_snapshots",
    "JobSchemaName": "kube_jobs",
    "LogSchemaName": "kube_logs",
    "EpSchemaName": "kube_endpoints",
    "NsSchemaName": "kube_ns_snapshots",
    "RqSchemaName": "kube_rq_snapshots",
    "DeploySchemaName": "kube_deploy_snapshots",
    "RSSchemaName": "kube_rs_snapshots",
    "DaemonSchemaName": "kube_daemon_snapshots",
    "DashboardTemplatePath": "/opt/appdynamics/templates/cluster-template.json",
    "DashboardSuffix": "SUMMARY",
    "DashboardDelayMin": 2,
    "AgentLabel": "appd-agent",
    "AgentEnvVar": "JAVA_OPTS",
    "AppDAppLabel": "appd-app",
    "AppDTierLabel": "appd-tier",
    "AppDAnalyticsLabel": "appd-biq",
    "AgentMountName": "appd-agent-repo",
    "AgentMountPath": "/opt/appdynamics",
    "AppLogMountName": "appd-volume",
    "AppLogMountPath": "/opt/appdlogs",
    "JDKMountName": "jdk-repo",
    "JDKMountPath": "$JAVA_HOME/lib",
    "NodeNamePrefix": "node",
    "AnalyticsAgentUrl": "http://analytics-proxy:9090",
    "AnalyticsAgentContainerName": "appd-analytics-agent",
    "AppDInitContainerName": "appd-agent-attach",
    "AnalyticsAgentImage": "docker.io/appdynamics/analytics-agent:latest",
    "AppDJavaAttachImage": "docker.io/appdynamics/java-agent:latest",
    "AppDDotNetAttachImage": "docker.io/appdynamics/dotnet-core-agent:latest",
    "ProxyInfo": "",
    "ProxyUser": "",
    "ProxyPass": "",
    "InstrumentationMethod": "mountEnv",
    "InstrumentMatchString": [""],
    "DefaultInstrumentationTech": "java",
    "BiqService": "none",
    "InstrumentContainer": "first",
    "InitContainerDir": "/opt/temp",
    "MetricsSyncInterval": {{ .Values.agent.metricsSyncInterval }},
    "SnapshotSyncInterval": {{ .Values.agent.snapshotSyncInterval }},
    "AgentServerPort": {{ .Values.agent.agentServerPort }},
    "NsToMonitor": [],
    "NsToMonitorExclude": [],
    "DeploysToDashboard": [],
    "NodesToMonitor": [],
    "NodesToMonitorExclude": [],
    "NsToInstrument": [],
    "NsToInstrumentExclude": [],
    "NSInstrumentRule": [{"Namespaces":["dev"],"MatchString":["dotnet"],"Tech": "dotnet", "AppDAppLabel":"name"},
    {"Namespaces":["dev"],"MatchString":["client-api"],"BiQ": "sidecar", "AppDAppLabel":"name"}],
    "InitRequestMem": "50",
    "InitRequestCpu": "0.1",
    "BiqRequestMem": "600",
    "BiqRequestCpu": "0.1",
    "LogLines": 0,
    "PodEventNumber": 1,
    "LogLevel": {{ .Values.agent.logLevel | quote}},
    "OverconsumptionThreshold": 80
    }
kind: ConfigMap
metadata:
  name: cluster-agent-config
  namespace: {{ .Release.Namespace }}
