{{- if .Values.controller.apiUser }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-secret
  labels:
    app: {{ template "cluster-agent.name" . }}
    chart: {{ template "cluster-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  api-user: {{ .Values.controller.apiUser | b64enc | quote }}
{{- if .Values.controller.controllerKey }}
  controller-key: {{ .Values.controller.controllerKey | b64enc | quote }}
{{- end }}
{{- if .Values.controller.eventKey }}
  event-key: {{ .Values.controller.eventKey | b64enc | quote }}
{{- end }}
{{- end }}
