apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
    helm.sh/chart: {{ include "cluster-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.agent.agentServerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}