# Default values for kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Lists the secrets you need to use to pull kafka-operator image from a private registry.
imagePullSecrets: []
  # - private-registry-key

operator:
  image:
    repository: banzaicloud/kafka-operator
    tag: 0.6.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

alertManager:
  enable: true

prometheusMetrics:
  enabled: true
  authProxy:
    enabled: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.4.0
      pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true

nodeSelector: {}

tolerations: []

affinity: {}
