apiVersion: v1
appVersion: 4.1.8
description: qBittorrent is a cross-platform free and open-source BitTorrent client
home: https://github.com/billimek/billimek-charts/tree/master/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
keywords:
- qbittorrent
- torrrent
maintainers:
- email: jeff@billimek.com
  name: billimek
name: qbittorrent
sources:
- https://hub.docker.com/r/linuxserver/qbittorrent/
version: 1.0.0
