apiVersion: v1
appVersion: 0.9.1
description: A Helm chart for prometheus pushgateway
home: https://github.com/prometheus/pushgateway
keywords:
- pushgateway
- prometheus
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
name: prometheus-pushgateway
sources:
- https://github.com/prometheus/pushgateway
version: 1.0.1
