apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hive.labels" . | indent 4 }}
type: Opaque
data:
  dsn: {{ .Values.hive.config.dsn | b64enc | quote }}
  # Generate a random secret if the user doesn't give one. User given password has priority
  secretsSession: {{ include "hive.secrets.session" . | required "Value hive.config.secrets.session can not be empty!" | b64enc | quote }}
