apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"  
    lenses.io/app.type: lenses-secret  
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.redis.password: {{ .Values.password | b64enc }}
  {{- if .Values.sslEnabled }}
  connect.redis.truststore.pass: {{ .Values.trustStorePass | default "" | b64enc }}
  connect.redis.keystore.pass: {{ .Values.keyStorePass | default "" | b64enc }}
  client.truststore.jks: |-
{{ .Values.trustStoreFileData  | indent 4 }}
  client.keystore.jks: |-
{{ .Values.keyStoreFileData  | indent 4 }}
  {{- end }}
