# Basic info
replicaCount: 1

image:
  repository: streamreactor/bloomberg
  tag: 1.2.2
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

podManagementPolicy: OrderedReady

# kafka ssl
# The key and truststores file data are the base64 encoded contents of the files. YOU MUST PROVIDE THE DATA BASE64 encoded
# and added to the kafka secret and mounted into /mnt/connector-secrets
kafka:
  # replicationFactor for connect topics
  replicationFactor: 3
  securityProtocol:
  ssl:
    enabled: false
    trustStoreFileData:
    trustStorePassword:
    keyStoreFileData:
    keyStorePassword:
  sasl:
    enabled: false
    # keyTabData is the contents kerberos keytab file is using kerberos
    keyTabData: |-
             
    # jaasFileData is the contents of the kafka jaas file
    jaasFileData: |-
          
    #GSSAPI, SCRAM or PLAIN
    mechanism: GSSAPI
    # kerberos krb5 contents
    krb5Conf: |-

  bootstrapServers: 
    - name: kafka
      port: 9092
      sslPort: 9093
      saslSslPort: 9094
      saslPlainTextPort: 9095       

schemaRegistries:
  enabled: true
  hosts:
    - host: schema-registry
      protocol: http
      port: 8081
      jmxPort: 9102  
        
# secretsProvider is either env (k8), vault (hashicorp) or azure (keyvault)
secretsProvider: env

# javaHeap options    
javaHeap: 256M

# clusterName The connect cluster name. This is the consumer group id for the backing topics
clusterName: "__REQUIRED__"

# restPort The rest port of Connect
restPort: 8083

# logLevel The log4j level
logLevel: INFO

# keyConverter The key converter to/from Connects struct
keyConverter: "io.confluent.connect.avro.AvroConverter"

# valueConverter The key converter to/from Connects struct
valueConverter: "io.confluent.connect.avro.AvroConverter"

# connectorClass
connectorClass: "com.datamountaineer.streamreactor.connect.bloomberg.BloombergSourceConnector"

# applicationId name of the connector
applicationId: "__REQUIRED__"

# enabled Enables the output for how many records have been processed type: BOOLEAN importance: MEDIUM
progressEnabled: true

# payloadType Specifies the way the information is serialized and sent over kafka. There are two modes supported: json(default) and avro. type: STRING importance: MEDIUM
payloadType: "__REQUIRED__"

# bufferSize Specifies how big is the queue to hold the updates received from Bloomberg. If the buffer is fullit won't accept new items until it is drained. type: INT importance: MEDIUM
bufferSize: "__REQUIRED__"

# kafkaTopic The name of the kafka topic on which the data from Bloomberg will be sent. type: STRING importance: HIGH
kafkaTopic: "__REQUIRED__"

# authenticationMode Optional parameter setting how the authentication should be done. It can be APPLICATION_ONLY or USER_AND_APPLICATION. Follow the Bloomberg API documentation for how to configure this type: STRING importance: LOW
authenticationMode: "__REQUIRED__"

# serverHost The hostname running the bloomberg service type: STRING importance: HIGH
serverHost: "__REQUIRED__" 

# serverPort The port on which the bloomberg service runs (8124-is the default) type: INT importance: HIGH 
serverPort: "__REQUIRED__"

# serviceUri The Bloomberg service type: Market Data(//blp/mktdata);Reference Data(//blp/refdata) type: STRING importance: HIGH
serviceUri: "__REQUIRED__"

# subscriptions Provides the list of securities and the fields to subscribe to. Example: "AAPL US Equity:LAST_PRICE,BID,ASK;IBM US Equity:BID,ASK,HIGH,LOW,OPEN" type: STRING importance: HIGH
subscriptions: "__REQUIRED__"