appVersion: 3.12.2
description: Hazelcast IMDG Enterprise is the most widely used in-memory data grid
  with hundreds of thousands of installed clusters around the world. It offers caching
  solutions ensuring that data is in the right place when it’s needed for optimal
  performance.
engine: gotpl
home: https://hazelcast.com/products/enterprise/
icon: http://hazelcast.com/images/logos/Hazelcast-IMDG-Logo-Blue_Dark_Icon_200px.png
keywords:
- hazelcast
- keyvalue
- in-memory
- database
- caching
kubeVersion: '>=1.9.0-0'
maintainers:
- email: rafal@hazelcast.com
  name: leszko
- email: guglielmo@hazelcast.com
  name: googlielmo
- email: mesut@hazelcast.com
  name: mesutcelik
name: hazelcast-enterprise
tillerVersion: '>=2.7.2'
version: 1.10.3
