apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-autocert-config
  namespace: {{.Release.Namespace}}
  labels: 
{{ include "autocert.labels" . | indent 4 }}
data:
  config.yaml: |
    address: :{{.Values.service.targetPort}}
    service: {{ include "autocert.fullname" . }}
    logFormat: {{.Values.autocert.logFormat}}
    caUrl: {{ include "autocert.ca.url" . }}
    certLifetime: {{.Values.autocert.certLifetime}}
    clusterDomain: {{.Values.autocert.clusterDomain}}
    restrictCertificatesToNamespace: {{.Values.autocert.restrictCertificatesToNamespace}}
    rootCAPath: /home/step/certs/root_ca.crt
    provisionerPasswordPath: /home/step/password/password
    renewer:
      name: autocert-renewer
      image: {{.Values.renewer.image.repository}}:{{.Values.renewer.image.tag}}
      imagePullPolicy: {{.Values.renewer.image.pullPolicy}}
      resources:
        {{- toYaml .Values.renewer.resources | nindent 8 }}
      volumeMounts:
      - name: certs
        mountPath: /var/run/autocert.step.sm
    bootstrapper:
      name: autocert-bootstrapper
      image: {{.Values.bootstrapper.image.repository}}:{{.Values.bootstrapper.image.tag}}
      imagePullPolicy: {{.Values.bootstrapper.image.pullPolicy}}
      resources:
        {{- toYaml .Values.bootstrapper.resources | nindent 8 }}
      volumeMounts:
      - name: certs
        mountPath: /var/run/autocert.step.sm
    certsVolume:
      name: certs
      emptyDir: {}
