appVersion: 0.6.0
description: The proxy server for Go modules
engine: gotpl
home: https://github.com/gomods/athens
icon: https://raw.githubusercontent.com/gomods/athens/master/docs/static/banner.png
keywords:
- Golang
- Package Management
- Goproxy
maintainers:
- email: rmocius@gmail.com
  name: rimusz
- email: aaron@ecomaz.net
  name: arschles
name: athens-proxy
version: 0.3.3
