apiVersion: v1
appVersion: 5.9.0
description: Mattermost Push Proxy server
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
keywords:
- mattermost
- communication
- notification
- messaging
- team colaboration
maintainers:
- email: carlos@mattermost.com
  name: cpanato
- email: joram@mattermost.com
  name: jwilander
name: mattermost-push-proxy
version: 0.2.3
