# requirements.yaml
dependencies:
# - name: kafka
#   version: 0.7.2
#   repository: http://storage.googleapis.com/kubernetes-charts-incubator
#   alias: kafka
#   condition: kafka.enabled
- name: mongodb
  version: 4.9.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mongodb
  condition: mongodb.enabled
