apiVersion: v1
appVersion: 0.15.39
description: Factorio dedicated server.
home: https://www.factorio.com/
icon: https://us1.factorio.com/assets/img/factorio-logo.png
keywords:
- game
- server
maintainers:
- email: gtaylor@gc-taylor.com
  name: gtaylor
name: factorio
sources:
- https://github.com/games-on-k8s/docker-factorio
version: 1.0.0
