apiVersion: v1
appVersion: 0.5.0
description: A Helm chart for prometheus-nats-exporter
home: https://github.com/nats-io/prometheus-nats-exporter
keywords:
- nats
- prometheus
- exporter
maintainers:
- email: okgolove@markeloff.net
  name: okgolove
- email: carlos@carlosbecker.com
  name: caarlos0
name: prometheus-nats-exporter
sources:
- https://github.com/nats-io/prometheus-nats-exporter
version: 2.2.0
