apiVersion: v1
appVersion: v1.0.0-rc.14_oryOS.12
description: A Helm chart for deployoing ORY Hydra in Kubernetes
home: https://www.ory.sh/
keywords:
- oauth2
- openid-connect
- openid
- oidc
- op
- api-security
- security
maintainers:
- email: hi@ory.sh
  name: ORY Team
  url: https://www.ory.sh/
name: hydra
sources:
- https://github.com/ory/hydra
- https://github.com/ory/k8s
version: 0.0.35
