apiVersion: v1
appVersion: v0.32.0-beta.1
description: A Helm chart for deployoing ORY Oathkeeper in Kubernetes
home: https://www.ory.sh/
keywords:
- zero-trust
- beyond-corp
- access-control
- reverse-proxy
- nginx
- envoy
- ambassador
- auth-filter
maintainers:
- email: hi@ory.sh
  name: ORY Team
  url: https://www.ory.sh/
name: oathkeeper
sources:
- https://github.com/ory/oathkeeper
- https://github.com/ory/k8s
version: 0.0.35
