{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cron-schedules.serviceAccountName" . }}
  labels:
{{ include "cron-schedules.labels.standard" . | indent 4 }}
{{- end -}}
