{{- if .Values.grafana.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "grafana.name" . }}
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
{{- end }}
