{{- if .Values.grafana.enabled }}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "grafana.fullname" . }}
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
spec:
  targets:
    - name: {{ include "grafana.fullname" . }}
  peers:
    - mtls:
        mode: PERMISSIVE
  {{- end }}
