{{- if .Values.useNamespaceResource }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    istio-injection: enabled
  name: {{ .Release.Namespace }}
{{- end }}
