apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "prometheus.name" . }}
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: {{ include "prometheus.name" . }}
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: {{ include "prometheus.name" . }}
    app.kubernetes.io/name: {{ include "prometheus.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "prometheus.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
