{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.global.scrapeInterval }}
      scrape_timeout: {{ .Values.prometheus.config.global.scrapeTimeout }}
      evaluation_interval: {{ .Values.prometheus.config.global.evaluationInterval }}
    rule_files:
    - /etc/prometheus/*_rules.yml
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: istio-mesh
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-telemetry;prometheus
        action: keep
    - job_name: istio-policy
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-policy;http-monitoring
        action: keep
    - job_name: istio-telemetry
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-telemetry;http-monitoring
        action: keep
    - job_name: pilot
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-pilot;http-monitoring
        action: keep
    - job_name: galley
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-galley;http-monitoring
        action: keep
    - job_name: envoy-stats
      scrape_interval: 1s
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        regex: .*-envoy-prom
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: ([^:]+)(?::\d+)?;(\d+)
        target_label: __address__
        replacement: $1:15090
        action: replace
      - regex: __meta_kubernetes_pod_label_(.+)
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
        action: replace
      metric_relabel_configs:
      - source_labels: [cluster_name]
        regex: (outbound|inbound|prometheus_stats).*
        action: drop
      - source_labels: [tcp_prefix]
        regex: (outbound|inbound|prometheus_stats).*
        action: drop
      - source_labels: [listener_address]
        regex: (.+)
        action: drop
      - source_labels: [http_conn_manager_listener_prefix]
        regex: (.+)
        action: drop
      - source_labels: [http_conn_manager_prefix]
        regex: (.+)
        action: drop
      - source_labels: [__name__]
        regex: envoy_tls.*
        action: drop
      - source_labels: [__name__]
        regex: envoy_tcp_downstream.*
        action: drop
      - source_labels: [__name__]
        regex: envoy_http_(stats|admin).*
        action: drop
      - source_labels: [__name__]
        regex: envoy_cluster_(lb|retry|bind|internal|max|original).*
        action: drop
{{- end }}
