{{ if .Values.tracing.enabled}}
  {{ if eq .Values.tracing.provider "jaeger" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backyards.name" . }}-{{ .Values.tracing.provider }}-query
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.tracing.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: {{ .Values.tracing.provider }}
    app.kubernetes.io/name: {{ .Values.tracing.provider }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: {{ .Values.tracing.provider }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backyards.name" . }}-{{ .Values.tracing.provider }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tracing.provider }}
    app.kubernetes.io/name: {{ .Values.tracing.provider }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
spec:
  ports:
  - name: {{ include "backyards.name" . }}-{{ .Values.tracing.provider }}-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: {{ .Values.tracing.provider }}-collector-http
    port: 14268
    targetPort: 14268
    protocol: TCP
  selector:
    app: {{ .Values.tracing.provider }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backyards.name" . }}-{{ .Values.tracing.provider }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tracing.provider }}
    app.kubernetes.io/name: {{ .Values.tracing.provider }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  clusterIP: None
  selector:
    app: {{ .Values.tracing.provider }}
{{ end }}
{{ end }}
