{{- if .Values.tracing.enabled }}
{{- if eq .Values.tracing.provider "jaeger" }}
{{- if .Values.tracing.jaeger.persist }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "backyards.name" . }}-jaeger-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.tracing.provider }}
    app.kubernetes.io/name: {{ .Values.tracing.provider }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
spec:
  storageClassName: {{ .Values.tracing.jaeger.storageClassName }}
  accessModes:
    - {{ .Values.tracing.jaeger.accessMode }}
  resources:
    requests:
      storage: 5Gi
{{- end }}
{{- end }}
{{- end }}
