# Basic info
replicaCount: 1

image:
  repository: streamreactor/elastic
  tag: 1.2.2
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
    
# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

podManagementPolicy: OrderedReady

# kafka ssl
# The key and truststores file data are the base64 encoded contents of the files. YOU MUST PROVIDE THE DATA BASE64 encoded
# and added to the kafka secret and mounted into /mnt/connector-secrets
kafka:
  # replicationFactor for connect topics
  replicationFactor: 3
  securityProtocol:
  ssl:
    enabled: false
    trustStoreFileData:
    trustStorePassword:
    keyStoreFileData:
    keyStorePassword:
  sasl:
    enabled: false
    # keyTabData is the contents kerberos keytab file is using kerberos
    keyTabData: |-
             
    # jaasFileData is the contents of the kafka jaas file
    jaasFileData: |-
          
    #GSSAPI, SCRAM or PLAIN
    mechanism: GSSAPI
    # kerberos krb5 contents
    krb5Conf: |-

  bootstrapServers: 
    - name: kafka
      port: 9092
      sslPort: 9093
      saslSslPort: 9094
      saslPlainTextPort: 9095       

schemaRegistries:
  enabled: true
  hosts:
    - host: schema-registry
      protocol: http
      port: 8081
      jmxPort: 9102    
    
# secretsProvider is either env (k8), vault (hashicorp) or azure (keyvault)
secretsProvider: env

#javaHeap option
javaHeap: "256M"

# clusterName The connect cluster name. This is the consumer group id for the backing topics
clusterName: "__REQUIRED__"

# restPort The rest port of Connect
restPort: 8083

# logLevel The log4j level
logLevel: INFO

# keyConverter The key converter to/from Connects struct 
keyConverter: "io.confluent.connect.avro.AvroConverter"

# valueConverter The key converter to/from Connects struct
valueConverter: "io.confluent.connect.avro.AvroConverter"

# applicationId name of the connector
applicationId: "__REQUIRED__"

# connectorClass
connectorClass: "com.datamountaineer.streamreactor.connect.elastic.ElasticSinkConnector"

# topics to sink
topics: "__REQUIRED__"

# kcql KCQL expression describing field selection and routes. type: STRING importance: HIGH
kcql: "__REQUIRED__"

# errorThrow Throws the exception on write. Default is 'true' type: BOOLEAN importance: MEDIUM
errorThrow: true

# enabled Enables the output for how many records have been processed type: BOOLEAN importance: MEDIUM
progressEnabled: true

# clusterName Name of the elastic search cluster, used in local mode for setting the connection type: STRING importance: HIGH
elasticClusterName: elasticsearch

# writeTimeout The time to wait in millis. Default is 5 minutes. type: INT importance: MEDIUM
writeTimeout: 300000

# uriPrefix URL connection string prefix type: STRING importance: LOW
uriPrefix: elasticsearch

# uri Url including port for Elastic Search cluster node. type: STRING importance: HIGH
uri: localhost:9300


