apiVersion: v1
appVersion: 0.14.0
description: Prometheus Blackbox Exporter
home: https://github.com/prometheus/blackbox_exporter
keywords:
- prometheus
- blackbox
- monitoring
maintainers:
- email: cedric@desaintmartin.fr
  name: desaintmartin
- email: gianrubio@gmail.com
  name: gianrubio
name: prometheus-blackbox-exporter
sources:
- https://github.com/prometheus/blackbox_exporter
version: 1.0.0
