apiVersion: v1
appVersion: amd64-v0.2.0.1344-ls17
description: Radarr is a movie downloading client
home: https://github.com/billimek/billimek-charts/tree/master/radarr
icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
keywords:
- radarr
- usenet
- bittorrent
maintainers:
- email: jeff@billimek.com
  name: billimek
name: radarr
sources:
- https://hub.docker.com/r/linuxserver/radarr/
- https://github.com/Radarr/Radarr/
version: 2.0.8
