name: "__REQUIRED__"
# storageClass name of the storage class
storageClassName: "__REQUIRED__"
# capacity of the storage e.g. 10Gi
capacity: "__REQUIRED__"
# Access mode, read and write from many pods, needs to match the volume spec
accessMode: "ReadWriteMany"