appVersion: 1.17.3
description: A simple, powerful publishing platform that allows you to share your
  stories with the world
engine: gotpl
home: http://www.ghost.org/
icon: https://bitnami.com/assets/stacks/ghost/img/ghost-stack-220x234.png
keywords:
- ghost
- blog
- http
- web
- application
- nodejs
- javascript
maintainers:
- email: ritazh@microsoft.com
  name: Rita Zhang
name: azu-ghost
sources:
- https://github.com/bitnami/bitnami-docker-ghost
version: 0.5.0
