apiVersion: v1
kind: Service
metadata:
  name: {{ include "centraleventprocessor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "centraleventprocessor.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "centraleventprocessor.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
