---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "swagger-ui.fullname" . }}
  labels:
    app: {{ template "swagger-ui.name" . }}
    chart: {{ template "swagger-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "swagger-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.swaggerui.jsonPath }}
          volumeMounts:
          - mountPath: /api-doc
            name: swagger-config
          {{ else }}
          command: ["/bin/sh","-c"]
          args : {{ (printf "[\"mkdir /api-doc && wget %s -O /api-doc/openapi.json && apk update && apk add jq && jq '.servers += [{\\\"url\\\":\\\"%s\\\",\\\"description\\\":\\\"%s\\\"}]' /api-doc/openapi.json > json.tmp && mv json.tmp /api-doc/openapi.json && /usr/share/nginx/run.sh\"]" .Values.swaggerui.jsonUrl .Values.swaggerui.server.url .Values.swaggerui.server.description ) }} {{ end }}
          env:
          - name: SWAGGER_JSON
            value: /api-doc/openapi.json
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.httpGet.port }}
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
            targetPort: http
      {{- if .Values.swaggerui.jsonPath }}
      volumes:
        - name: swagger-config
          configMap:
            name: {{ template "swagger-ui.fullname" . }}
            items:
            - key: conf.json
              path: openapi.json
      {{ end }}
