apiVersion: v1
description: A Helm chart to deploy Reflector
engine: gotpl
home: https://github.com/EmberStack/ES.Kubernetes.Reflector
icon: https://raw.githubusercontent.com/EmberStack/CDN/master/Projects/ES.FX/es.fx.1.0.0.0.png
keywords:
- reflector
- controller
- copy
- secrets
- configmaps
- cert-manager
- certificates
maintainers:
- email: helm-charts@emberstack.com
  name: winromulus
name: reflector
sources:
- https://github.com/EmberStack/ES.Kubernetes.Reflector
version: 2.19197.5
