apiVersion: v1
appVersion: 2.8.0
description: A Helm chart for owasp-zap
home: https://github.com/zaproxy/zaproxy
icon: https://banner2.kisspng.com/20180502/ozq/kisspng-owasp-zap-vulnerability-penetration-test-proxy-ser-web-application-5aea65947a30d0.0276627015253108685005.jpg
keywords:
- rclone
maintainers:
- name: zee-ahmed
name: kube-owasp-zap
sources:
- https://github.com/zee-ahmed/kube-owasp-zap
- https://hub.docker.com/r/owasp/zap2docker-stable/
version: 0.1.0
