apiVersion: v1
appVersion: 6.0.1
description: Keycloak gatekeeper
engine: gotpl
home: https://github.com/keycloak/keycloak-gatekeeper
icon: https://raw.githubusercontent.com/keycloak/keycloak-misc/master/logo/keycloak_logo_600px.png
keywords:
- authentication
- authorization
- keycloak
- proxy
maintainers:
- email: gabibbo97@gmail.com
  name: gabibbo97
name: keycloak-gatekeeper
version: 1.3.0
