apiVersion: v1
appVersion: 0.14.0
description: Chaoskube periodically kills random pods in your Kubernetes cluster.
engine: gotpl
home: https://github.com/linki/chaoskube
icon: https://raw.githubusercontent.com/linki/chaoskube/master/chaoskube.png
keywords:
- chaos-monkey
- chaos-engineering
maintainers:
- email: linki+kubernetes.io@posteo.de
  name: linki
- email: a.vicente.grab@gmail.com
  name: alexvicegrab
- email: syedimam0012@gmail.com
  name: syedimam0012
name: chaoskube
sources:
- https://github.com/linki/chaoskube
version: 3.1.2
