{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: {{ default "Opaque" .type }}
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "secret.name" $ }}
    chart: {{ template "secret.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{ with .labels -}}{{- toYaml . | indent 4 -}}{{- end }}
stringData:
{{ toYaml .values | indent 2 -}}
{{- end -}}
