description: Chart for Chronograf
engine: gotpl
home: https://www.influxdata.com/time-series-platform/chronograf/
keywords:
- chronograf
- visualizaion
- timeseries
maintainers:
- {}
- {}
name: inf-chronograf
version: 1.7.11
