apiVersion: v1
appVersion: v1.2.0
description: Prometheus metrics exporter for Kafka
home: https://gkarthiks.github.io/helm-charts/prometheus-kafka-exporter
keywords:
- prometheus
- kafka
maintainers:
- email: github.gkarthiks@gmail.com
  name: gkarthiks
name: prometheus-kafka-exporter
sources:
- https://github.com/danielqsj/kafka_exporter
version: 0.1.0
