---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
{{ include "mongodb.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: None
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
{{/*
Component specific services
*/}}
{{- range $i, $role := list "arbiter" "data" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" $ }}-{{ $role }}
  labels:
{{ include "mongodb.labels" $ | indent 4 }}
    app.kubernetes.io/component: {{ $role }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mongodb.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $role }}
  clusterIP: None
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ include "mongodb.port" $ }}
      targetPort: mongodb
{{- end }}