apiVersion: v1
appVersion: 2.0.2.0-b10
description: YugaWare is YugaByte Database's Orchestration and Management console.
home: https://www.yugabyte.com
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- email: ram@yugabyte.com
  name: Ram Sri
name: yugaware
version: 2.0.2
