apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: stardog
      port: 5820
      targetPort: stardog
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 80
      targetPort: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
