apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-user-passwords
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  admin: {{ required "A password for the stardog admin is required" .Values.stardog.adminPassword | b64enc | quote }}
  {{ range .Values.stardog.users }}
  {{ .name }}: {{ .password | b64enc | quote }}
  {{end}}
