apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "namespace.fullname" . }}
  labels:
    app: {{ template "namespace.name" . }}
    chart: {{ template "namespace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.magicnamespace.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "namespace.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
