apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-admin-group
  namespace: {{ .Values.magicnamespace.namespace }}
  labels:
    app: {{ template "namespace.name" . }}
    chart: {{ template "namespace.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: {{ .Values.roleBindings.groupPrefix }}{{ .Values.magicnamespace.namespace }}.admin
