apiVersion: v1
appVersion: 0.1.5
description: Helm chart to deploy AppDynamics ClusterAgent for Kubernetes
home: https://www.appdynamics.com/
icon: https://raw.githubusercontent.com/Appdynamics/appdynamics-charts/master/logo.png
keywords:
- appdynamics
- monitoring
- Kubernetes
- OpenShift
maintainers:
- email: sasha.jeltuhin@appdynamics.com
  name: sashaPM
name: cluster-agent
sources:
- https://github.com/Appdynamics/cluster-agent/blob/master/build/Dockerfile
version: 0.1.2
