apiVersion: v1
appVersion: 1.3.0.0-b1
description: YugaByte Database is the high-performance distributed SQL database for
  building global, internet-scale applications
home: https://www.yugabyte.com
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- email: ram@yugabyte.com
  name: Ram Sri
- email: arnav@yugabyte.com
  name: Arnav Agarwal
name: yugabyte
sources:
- https://github.com/yugabyte/yugabyte-db
version: 1.3.0
