{{- if .Values.hollowtreesNotifier.jwtToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instance-termination-handler.fullname" . }}
  labels:
{{ include "instance-termination-handler.labels" . | indent 4 }}
type: Opaque
data:
  tokenSigningKey: {{ .Values.hollowtreesNotifier.jwtToken | b64enc | quote }}
{{- end }}
