kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "mongo-pod-labeler.name" . }}
    helm.sh/chart: {{ include "mongo-pod-labeler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "mongo-pod-labeler.clusterrole" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "patch", "list"]

