apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "mongo-pod-labeler.name" . }}
    helm.sh/chart: {{ include "mongo-pod-labeler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "mongo-pod-labeler.serviceaccount" . }}
  namespace: {{ .Values.namespace }}
