# Default values for flagger.

image:
  repository: weaveworks/flagger
  tag: 0.20.1
  pullPolicy: IfNotPresent
  pullSecret:

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

metricsServer: "http://prometheus:9090"

# accepted values are kubernetes, istio, linkerd, appmesh, nginx, gloo or supergloo:mesh.namespace (defaults to istio)
meshProvider: ""

# single namespace restriction
namespace: ""

# list of pod labels that Flagger uses to create pod selectors
# defaults to: app,name,app.kubernetes.io/name
selectorLabels: ""

slack:
  user: flagger
  channel:
  # incoming webhook https://api.slack.com/incoming-webhooks
  url:

msteams:
  # MS Teams incoming webhook URL
  url:

#env:
#- name: SLACK_URL
#  valueFrom:
#    secretKeyRef:
#      name: slack
#      key: url
#- name: MSTEAMS_URL
#  valueFrom:
#    secretKeyRef:
#      name: msteams
#      key: url
env: []

leaderElection:
  enabled: false
  replicaCount: 1

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: true
  # serviceAccount.name: The name of the service account to create or use
  name: ""

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: true
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

crd:
  # crd.create: `true` if custom resource definitions should be created
  create: true

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    memory: "512Mi"
    cpu: "1000m"
  requests:
    memory: "32Mi"
    cpu: "10m"

nodeSelector: {}

tolerations: []

prometheus:
  # to be used with AppMesh or nginx ingress
  install: false
