serviceAccountName: sloop
name: sloop
replicas: 1
image:
  tag: 1b3abc15c548316819720124f5f2c3d232d81176
  repository: honestica/sloop
persistentVolume:
## If defined it will specify the storageClass for the statefulSet
## If undefined it will use the cluster default (typically gp2 on AWS, standard on GKE)
#  storageClass: 
  size: 10Gi
  dataAccessMode: ReadWriteOnce
  sizeLimit: 12Gi
resources: {}
service:
  port: 80
  targetPort: 8080
## Configure extra options for liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
