apiVersion: v1
appVersion: "1.0"
description: Dynamic DNS using DigitalOcean's DNS Services
home: https://github.com/billimek/billimek-charts/tree/master/digitalocean-dyndns
icon: https://i.imgur.com/cS6iqXD.png
keywords:
- digitalocean
- dynamicdns
maintainers:
- email: jeff@billimek.com
  name: billimek
name: digitalocean-dyndns
sources:
- https://github.com/tunix/digitalocean-dyndns
- https://github.com/billimek/billimek-charts
version: 0.1.5
