{{- if and .Values.kafka.saslEnabled (eq .Values.kafka.sasl.mechanism "GSSAPI") }}

kind: ConfigMap
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-configmap
    lenses.io/pipeline: {{ .Values.monitoring.pipeline | quote }}    
data:
  krb5.conf: |-
{{ .Values.kafka.sasl.krb5Conf | indent 4 }} 
{{- end -}}