apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-headless
  labels:
    app: {{ include "fullname" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-service
    lenses.io/pipeline: {{ .Values.monitoring.pipeline | quote }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: runner
    port: 8083
  clusterIP: None
  selector:
    app: {{ include "fullname" . | quote }}
    release: {{ .Release.Name | quote }}