apiVersion: v1
appVersion: 1.1.1
description: Hoverfly is a lightweight, open source API simulation tool. Using Hoverfly,
  you can create realistic simulations of the APIs your application depends on.
home: https://hoverfly.io
keywords:
- hoverfly
- api-simulation
- mocking
- stubbing
- service-virtualization
maintainers:
- email: tommy.situ@specto.io
  name: tommysitu
name: hoverfly
sources:
- https://github.com/SpectoLabs/hoverfly
version: 0.1.1
