image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .

release-chart:
  stage: release
  script:
    - curl --fail --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  only:
    - master
