apiVersion: v1
appVersion: "1.6"
description: An Open-Source antivirus engine for detecting trojans, viruses, malware
  & other malicious threats.
home: https://www.clamav.net
icon: https://www.clamav.net/assets/clamav-trademark.png
maintainers:
- email: zakkg3@gmail.com
  name: zakkg3
name: clamav
version: 1.0.3
