basic_auth: true

faasnetes:
  image: openfaas/faas-netes:0.8.5-arm64

gateway:
  image: openfaas/gateway:0.17.0-arm64

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.17.0-arm64

queueWorker:
  image: openfaas/queue-worker:0.8.0-arm64

prometheus:
  image: functions/prometheus:2.7.1-arm64

alertmanager:
  image: functions/alertmanager:0.16.1-arm64

faasIdler:
  image: openfaas/faas-idler:0.2.1-arm64
