basic_auth: false

faasnetes:
  image: openfaas/faas-netes:0.8.5-armhf

gateway:
  image: openfaas/gateway:0.17.0-armhf

queueWorker:
  image: openfaas/queue-worker:0.8.0-armhf

prometheus:
  image: functions/prometheus:2.7.1-armhf
  resources:
    requests:
      memory: "125Mi"

alertmanager:
  image: functions/alertmanager:0.16.1-armhf

faasIdler:
  image: openfaas/faas-idler:0.2.0-armhf

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.17.0-armhf
  replicas: 1

