apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    lenses.io/app.type: lenses-secret    
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.mqtt.password: {{ .Values.password | b64enc }}
  {{- if .Values.tlsEnabled }}
  server.crt: {{ .Values.serverCrt | b64enc }}
  ca.crt: {{ .Values.caCert | b64enc }}
  server.key: {{ .Values.serverKey | b64enc }}
  {{- end -}}
