{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
{{ toYaml .Values.rbac.role.rules | indent 2 }}
{{- end }}
