{{- if .Values.podSecurityPolicy.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "orchestrator.fullname" . }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "orchestrator.fullname" . }}
{{- end }}
