apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "nginx-logging-loki-demo.fullname" . }}-logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: {{ .Release.Namespace }}
