{{- $name := .Chart.Name -}}
{{- $version := .Chart.Version -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- range .Values.services }}
kind: Service
metadata:
  name: {{ .host }}
  {{- if .annotations }}
  annotations:
  {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    chart: "{{ $name }}-{{ $version}}"
    release: "{{ $releaseName }}"
    heritage: "{{ $releaseService }}"
spec:
  sessionAffinity: ClientIP
  ports:
  {{- range .ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
  {{- end }}
---
{{- end }}

