apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ip-geo-locator.fullname" . }}
  labels:
{{ include "ip-geo-locator.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "ip-geo-locator.labels.standard" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "ip-geo-locator.labels.standard" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "ip-geo-locator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value }}
{{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
{{ toYaml .Values.livenessProbe.probe | indent 10}}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
{{ toYaml .Values.readinessProbe.probe | indent 10}}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
