{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ip-geo-locator.serviceAccountName" . }}
  labels:
{{ include "ip-geo-locator.labels.standard" . | indent 4 }}
{{- end -}}
