apiVersion: v1
appVersion: 19.10.1
description: A Helm chart for kube-downscaler
home: https://github.com/hjacobs/kube-downscaler
keywords:
- k8s pods scheduler
- scheduled lifecycle
maintainers:
- email: c.tresarrieu@gmail.com
  name: Rowern
name: kube-downscaler
sources:
- https://github.com/hjacobs/kube-downscaler
version: 0.2.1
